notifications:
  email : false

sudo : false

language : c

matrix:
  fast_finish : true
  include:
    name : 8-2019-q3
    env : GCC_URL=https://developer.arm.com/-/media/Files/downloads/gnu-rm/8-2019q3/RC1.1/gcc-arm-none-eabi-8-2019-q3-update-linux.tar.bz2?revision=c34d758a-be0c-476e-a2de-af8c6e16a8a2?product=GNU%20Arm%20Embedded%20Toolchain,64-bit,,Linux,8-2019-q3-update

install:
  - pushd .
  - cd ~
  - mkdir arm-gcc-compiler
  - wget -O $HOME/arm-gcc-compiler/gcc.tar.bz2 $GCC_URL
  - cd arm-gcc-compiler
  - tar -jxf gcc.tar.bz2 --strip=1
  - popd
  - export PATH=$HOME/arm-gcc-compiler/bin:$PATH

before_script:
  - arm-none-eabi-gcc --version

script:
  - make