DRIVERSCPPSRC = $(AUTOCARPROJECT)/drivers/spidevice.cpp \
                $(AUTOCARPROJECT)/drivers/mpu6000.cpp

DRIVERSINC = $(AUTOCARPROJECT)/drivers

ALLCPPSRC += $(DRIVERSCPPSRC)
ALLINC += $(DRIVERSINC)
